### ISSUE TITLE
目前无空闲该模型，请稍后再试，或者更换模型

### ISSUE THREAD

**Issue by rawchen** [1130600015/feishu-chatgpt#3]
normal账号池共1个账号
plus账号池共0个账号
也没登录使用但是机器人对话一直提示目前无空闲该模型，请稍后再试，或者更换模型

**Comment by jiashu1024** [comment]
解决了？

**Comment by rawchen** [comment]
解决了，可能是前面的卡片权限没开，开了后重新起了程序就好了。不过现在有个null的错误
![image](https://github.com/1130600015/feishu-chatgpt/assets/43029287/7bc66c95-929a-43a8-a29a-5b0c7cc99718)

**Comment by jiashu1024** [comment]
> 解决了，可能是前面的卡片权限没开，开了后重新起了程序就好了。不过现在有个null的错误 ![image](https://user-images.githubusercontent.com/43029287/254201545-7bc66c95-929a-43a8-a29a-5b0c7cc99718.png)

这个不影响使用，这两天暂时没时间改这个bug

**Comment by jiashu1024** [comment]
为什么你3.5的模型能知道时间，我问了一遍我的 他说今天17号 害
